# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='visitor',
            field=models.TextField(),
        ),
    ]
