# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170821_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visitor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
